language: node_js
node_js:
  - node
  - 6
  - 4
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_install: npm install -g npm
script:
  - npm run bootstrap
  - npm run test
cache:
  yarn: true
