compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/eslint-plugin@*":
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
