name: Unit tests

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: install
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run tests
        run: yarn test
